# Generated by Django 4.1.2 on 2022-10-07 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de cuenta')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('date', models.DateField(verbose_name='Fecha de transacion')),
                ('income', models.BooleanField(verbose_name='Tipo de transacion')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transaction', to='transations.accountmodel', verbose_name='Cuenta de la transacion')),
            ],
            options={
                'verbose_name': 'Transacion',
                'verbose_name_plural': 'Transaciones',
                'ordering': ['date'],
            },
        ),
    ]
