# Generated by Django 4.1.2 on 2022-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de cuenta'),
        ),
    ]
