# Generated by Django 4.1.2 on 2022-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transations', '0002_alter_accountmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Descripcion'),
        ),
    ]
